# Generated by Django 4.2.3 on 2023-08-23 21:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etiquetas',
            new_name='Etiqueta',
        ),
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
